spring:
  # redis
  redis:
    password: 123456
    jedis:
      pool:
        max-wait: 1000ms
  # 数据库
  datasource:
    url: jdbc:mariadb://localhost:3306/edu_exam_sys
    password: achanyao
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    # database-pool
    hikari:
      max-lifetime: 30000
      connection-timeout: 60000

logging:
  level:
    ROOT: warn
    com:
      achan: debug
